"""initial schema

Revision ID: 16347b6d565d
Revises: 
Create Date: 2025-12-14 17:01:15.136628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16347b6d565d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    op.drop_table('airports')
    op.drop_table('navaids')
    op.drop_table('runways')
    op.drop_table('frequencies')
    op.drop_table('airport_types')
    op.drop_table('countries')
    op.drop_table('regions')
    op.drop_table('navid_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navid_types',
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code', name='navid_types_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('local_code', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('continent', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('iso_country', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('wikipedia_link', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code', name='regions_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('continent', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('wikipedia_link', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code', name='countries_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('airport_types',
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('code', name='airport_types_pk'),
    postgresql_ignore_search_path=False
    )
    op.create_table('frequencies',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('airport_ref', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('airport_ident', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('frequency_mhz', sa.REAL(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['airport_ident'], ['airports.ident'], name=op.f('frequencies_airports_fk'))
    )
    op.create_table('runways',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('airport_ref', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('airport_ident', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('length_ft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width_ft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('surface', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('lighted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('closed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('le_ident', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('le_latitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('le_longitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('le_elevation_ft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('le_heading_degt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('le_displaced_threshold_ft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('he_ident', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('he_latitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('he_longitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('he_elevation_ft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('he_heading_degt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('he_displaced_threshold_ft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['airport_ident'], ['airports.ident'], name=op.f('runways_airports_fk'))
    )
    op.create_table('navaids',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ident', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('frequency_khz', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('longitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('elevation_ft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iso_country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dme_frequency_khz', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dme_channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dme_latitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('dme_longitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('dme_elevation_ft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slaved_variation_deg', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('magnetic_variation_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('usagetype', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('power', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('associated_airport', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type'], ['navid_types.code'], name=op.f('navaids_navid_types_fk'))
    )
    op.create_table('airports',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ident', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('latitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('longitude_deg', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('elevation_ft', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('continent', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('iso_country', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('iso_region', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('municipality', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('scheduled_service', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('gps_code', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('iata_code', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('local_code', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('home_link', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('wikipedia_link', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['iso_country'], ['countries.code'], name=op.f('airports_countries_fk')),
    sa.ForeignKeyConstraint(['iso_region'], ['regions.code'], name=op.f('airports_regions_fk')),
    sa.ForeignKeyConstraint(['type'], ['airport_types.code'], name=op.f('airports_airport_types_fk')),
    sa.PrimaryKeyConstraint('ident', name=op.f('airports_pk'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey')),
    sa.UniqueConstraint('key', name=op.f('api_keys_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
